// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Parser$KanComp = require("./AnalisisSintactico/Parser.bs.js");
var Gramatica$KanComp = require("./AnalisisLexico/Gramatica.bs.js");

function repl(param) {
  console.log("> ");
  return /* () */0;
}

var entrada = "sea hola = 20";

var lexer = Gramatica$KanComp.crearLexer(entrada);

var expresion = Parser$KanComp.parseTokens(lexer);

console.log(expresion);

exports.repl = repl;
exports.entrada = entrada;
exports.lexer = lexer;
exports.expresion = expresion;
/* lexer Not a pure module */
