// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Parser$KanComp = require("./AnalisisSintactico/Parser.bs.js");
var Generador$KanComp = require("./Generador/Generador.bs.js");
var Gramatica$KanComp = require("./AnalisisLexico/Gramatica.bs.js");

function main(param) {
  var lexer = Gramatica$KanComp.crearLexer("sea mut hola = 20");
  var expresion = Parser$KanComp.parseTokens(lexer);
  if (expresion.tag) {
    console.log(expresion[0]);
    return /* () */0;
  } else {
    var js = Generador$KanComp.generarJs(expresion[0], true, 0);
    console.log(js);
    return /* () */0;
  }
}

main(/* () */0);

exports.main = main;
/*  Not a pure module */
