// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Parser$KanComp = require("./AnalisisSintactico/Parser.bs.js");
var Generador$KanComp = require("./Generador/Generador.bs.js");
var Gramatica$KanComp = require("./AnalisisLexico/Gramatica.bs.js");

function tknToStr(token2) {
  switch (token2.tag | 0) {
    case /* TNuevaLinea */0 :
        return "TNuevaLinea";
    case /* TIdentificador */1 :
        return "TIdentificador";
    case /* TGenerico */2 :
        return "TGenerico";
    case /* TComentario */3 :
        return "TComentario";
    case /* TNumero */4 :
        return "TNumero";
    case /* TTexto */5 :
        return "TTexto";
    case /* TBool */6 :
        return "TBool";
    case /* TOperador */7 :
        return "TOperador";
    case /* TParenAb */8 :
        return "TParenAb";
    case /* TParenCer */9 :
        return "TParenCer";
    case /* TAgrupAb */10 :
        return "TAgrupAb";
    case /* TAgrupCer */11 :
        return "TAgrupCer";
    case /* PC_LET */12 :
        return "PC_LET";
    case /* PC_CONST */13 :
        return "PC_CONST";
    
  }
}

function flujoPrincipal(entrada) {
  var lexer = Gramatica$KanComp.crearLexer(entrada);
  var expresion = Parser$KanComp.parseTokens(lexer);
  if (expresion.tag) {
    return expresion[0];
  } else {
    return Generador$KanComp.generarJs(expresion[0], true, 0)[0];
  }
}

exports.tknToStr = tknToStr;
exports.flujoPrincipal = flujoPrincipal;
/* Gramatica-KanComp Not a pure module */
